In [41]:
#Importing lib
import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression 

# Reading data
df = pd.read_csv("C:/Users/Kotti/Downloads/data.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    int64
 1   diagnosis                569 non-null    object
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             569 non-null    float64
 15  area_se                  569 non-null    float64
 16  smoothness_se            569 non-null    float64
 17  compactness_se           569 non-null    float64
 18  concavity_se             569 non-null    float64
 19  concave points_se        569 non-null    float64
 20  symmetry_se              569 non-null    float64
 21  fractal_dimension_se     569 non-null    float64
 22  radius_worst             569 non-null    float64
 23  texture_worst            569 non-null    float64
 24  perimeter_worst          569 non-null    float64
 25  area_worst               569 non-null    float64
 26  smoothness_worst         569 non-null    float64
 27  compactness_worst        569 non-null    float64
 28  concavity_worst          569 non-null    float64
 29  concave points_worst     569 non-null    float64
 30  symmetry_worst           569 non-null    float64
 31  fractal_dimension_worst  569 non-null    float64
 32  Unnamed: 32              0 non-null      float64
dtypes: float64(31), int64(1), object(1)
memory usage: 146.8+ KB

In [42]:
df.diagnosis

0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: object

In [43]:
# making label for diagnosis 

ln=LabelEncoder()

df.diagnosis=ln.fit_transform(df['diagnosis'])

df.diagnosis

0      1
1      1
2      1
3      1
4      1
      ..
564    1
565    1
566    1
567    1
568    0
Name: diagnosis, Length: 569, dtype: int32

In [44]:
#Finding correlation
df.corr()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
id,1.000000,0.039769,0.074626,0.099770,0.073159,0.096893,-0.012968,0.000096,0.050080,0.044158,...,0.064720,0.079986,0.107187,0.010338,-0.002968,0.023203,0.035174,-0.044224,-0.029866,NaN
diagnosis,0.039769,1.000000,0.730029,0.415185,0.742636,0.708984,0.358560,0.596534,0.696360,0.776614,...,0.456903,0.782914,0.733825,0.421465,0.590998,0.659610,0.793566,0.416294,0.323872,NaN
radius_mean,0.074626,0.730029,1.000000,0.323782,0.997855,0.987357,0.170581,0.506124,0.676764,0.822529,...,0.297008,0.965137,0.941082,0.119616,0.413463,0.526911,0.744214,0.163953,0.007066,NaN
texture_mean,0.099770,0.415185,0.323782,1.000000,0.329533,0.321086,-0.023389,0.236702,0.302418,0.293464,...,0.912045,0.358040,0.343546,0.077503,0.277830,0.301025,0.295316,0.105008,0.119205,NaN
perimeter_mean,0.073159,0.742636,0.997855,0.329533,1.000000,0.986507,0.207278,0.556936,0.716136,0.850977,...,0.303038,0.970387,0.941550,0.150549,0.455774,0.563879,0.771241,0.189115,0.051019,NaN
area_mean,0.096893,0.708984,0.987357,0.321086,0.986507,1.000000,0.177028,0.498502,0.685983,0.823269,...,0.287489,0.959120,0.959213,0.123523,0.390410,0.512606,0.722017,0.143570,0.003738,NaN
smoothness_mean,-0.012968,0.358560,0.170581,-0.023389,0.207278,0.177028,1.000000,0.659123,0.521984,0.553695,...,0.036072,0.238853,0.206718,0.805324,0.472468,0.434926,0.503053,0.394309,0.499316,NaN
compactness_mean,0.000096,0.596534,0.506124,0.236702,0.556936,0.498502,0.659123,1.000000,0.883121,0.831135,...,0.248133,0.590210,0.509604,0.565541,0.865809,0.816275,0.815573,0.510223,0.687382,NaN
concavity_mean,0.050080,0.696360,0.676764,0.302418,0.716136,0.685983,0.521984,0.883121,1.000000,0.921391,...,0.299879,0.729565,0.675987,0.448822,0.754968,0.884103,0.861323,0.409464,0.514930,NaN
concave points_mean,0.044158,0.776614,0.822529,0.293464,0.850977,0.823269,0.553695,0.831135,0.921391,1.000000,...,0.292752,0.855923,0.809630,0.452753,0.667454,0.752399,0.910155,0.375744,0.368661,NaN
symmetry_mean,-0.022114,0.330499,0.147741,0.071401,0.183027,0.151293,0.557775,0.602641,0.500667,0.462497,...,0.090651,0.219169,0.177193,0.426675,0.473200,0.433721,0.430297,0.699826,0.438413,NaN
fractal_dimension_mean,-0.052511,-0.012838,-0.311631,-0.076437,-0.261477,-0.283110,0.584792,0.565369,0.336783,0.166917,...,-0.051269,-0.205151,-0.231854,0.504942,0.458798,0.346234,0.175325,0.334019,0.767297,NaN
radius_se,0.143048,0.567134,0.679090,0.275869,0.691765,0.732562,0.301467,0.497473,0.631925,0.698050,...,0.194799,0.719684,0.751548,0.141919,0.287103,0.380585,0.531062,0.094543,0.049559,NaN
texture_se,-0.007526,-0.008303,-0.097317,0.386358,-0.086761,-0.066280,0.068406,0.046205,0.076218,0.021480,...,0.409003,-0.102242,-0.083195,-0.073658,-0.092439,-0.068956,-0.119638,-0.128215,-0.045655,NaN
perimeter_se,0.137331,0.556141,0.674172,0.281673,0.693135,0.726628,0.296092,0.548905,0.660391,0.710650,...,0.200371,0.721031,0.730713,0.130054,0.341919,0.418899,0.554897,0.109930,0.085433,NaN
area_se,0.177742,0.548236,0.735864,0.259845,0.744983,0.800086,0.246552,0.455653,0.617427,0.690299,...,0.196497,0.761213,0.811408,0.125389,0.283257,0.385100,0.538166,0.074126,0.017539,NaN
smoothness_se,0.096781,-0.067016,-0.222600,0.006614,-0.202694,-0.166777,0.332375,0.135299,0.098564,0.027653,...,-0.074743,-0.217304,-0.182195,0.314457,-0.055558,-0.058298,-0.102007,-0.107342,0.101480,NaN
compactness_se,0.033961,0.292999,0.206000,0.191975,0.250744,0.212583,0.318943,0.738722,0.670279,0.490424,...,0.143003,0.260516,0.199371,0.227394,0.678780,0.639147,0.483208,0.277878,0.590973,NaN
concavity_se,0.055239,0.253730,0.194204,0.143293,0.228082,0.207660,0.248396,0.570517,0.691270,0.439167,...,0.100241,0.226680,0.188353,0.168481,0.484858,0.662564,0.440472,0.197788,0.439329,NaN
concave points_se,0.078768,0.408042,0.376169,0.163851,0.407217,0.372320,0.380676,0.642262,0.683260,0.615634,...,0.086741,0.394999,0.342271,0.215351,0.452888,0.549592,0.602450,0.143116,0.310655,NaN
symmetry_se,-0.017306,-0.006522,-0.104321,0.009127,-0.081629,-0.072497,0.200774,0.229977,0.178009,0.095351,...,-0.077473,-0.103753,-0.110343,-0.012662,0.060255,0.037119,-0.030413,0.389402,0.078079,NaN
fractal_dimension_se,0.025725,0.077972,-0.042641,0.054458,-0.005523,-0.019887,0.283607,0.507318,0.449301,0.257584,...,-0.003195,-0.001000,-0.022736,0.170568,0.390159,0.379975,0.215204,0.111094,0.591328,NaN
radius_worst,0.082405,0.776454,0.969539,0.352573,0.969476,0.962746,0.213120,0.535315,0.688236,0.830318,...,0.359921,0.993708,0.984015,0.216574,0.475820,0.573975,0.787424,0.243529,0.093492,NaN
texture_worst,0.064720,0.456903,0.297008,0.912045,0.303038,0.287489,0.036072,0.248133,0.299879,0.292752,...,1.000000,0.365098,0.345842,0.225429,0.360832,0.368366,0.359755,0.233027,0.219122,NaN
perimeter_worst,0.079986,0.782914,0.965137,0.358040,0.970387,0.959120,0.238853,0.590210,0.729565,0.855923,...,0.365098,1.000000,0.977578,0.236775,0.529408,0.618344,0.816322,0.269493,0.138957,NaN
area_worst,0.107187,0.733825,0.941082,0.343546,0.941550,0.959213,0.206718,0.509604,0.675987,0.809630,...,0.345842,0.977578,1.000000,0.209145,0.438296,0.543331,0.747419,0.209146,0.079647,NaN
smoothness_worst,0.010338,0.421465,0.119616,0.077503,0.150549,0.123523,0.805324,0.565541,0.448822,0.452753,...,0.225429,0.236775,0.209145,1.000000,0.568187,0.518523,0.547691,0.493838,0.617624,NaN
compactness_worst,-0.002968,0.590998,0.413463,0.277830,0.455774,0.390410,0.472468,0.865809,0.754968,0.667454,...,0.360832,0.529408,0.438296,0.568187,1.000000,0.892261,0.801080,0.614441,0.810455,NaN
concavity_worst,0.023203,0.659610,0.526911,0.301025,0.563879,0.512606,0.434926,0.816275,0.884103,0.752399,...,0.368366,0.618344,0.543331,0.518523,0.892261,1.000000,0.855434,0.532520,0.686511,NaN
concave points_worst,0.035174,0.793566,0.744214,0.295316,0.771241,0.722017,0.503053,0.815573,0.861323,0.910155,...,0.359755,0.816322,0.747419,0.547691,0.801080,0.855434,1.000000,0.502528,0.511114,NaN
symmetry_worst,-0.044224,0.416294,0.163953,0.105008,0.189115,0.143570,0.394309,0.510223,0.409464,0.375744,...,0.233027,0.269493,0.209146,0.493838,0.614441,0.532520,0.502528,1.000000,0.537848,NaN
fractal_dimension_worst,-0.029866,0.323872,0.007066,0.119205,0.051019,0.003738,0.499316,0.687382,0.514930,0.368661,...,0.219122,0.138957,0.079647,0.617624,0.810455,0.686511,0.511114,0.537848,1.000000,NaN
Unnamed: 32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [45]:
# Assigning inputs and output
X_features={'radius_mean','perimeter_mean','concave points_worst','concave points_mean','perimeter_worst','area_worst'}
y=df['diagnosis']

In [46]:
X = df[X_features]
X

C:\Users\Kotti\AppData\Local\Temp\ipykernel_5148\186396290.py:1: FutureWarning: Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead.
  X = df[X_features]

,radius_mean,area_worst,concave points_mean,perimeter_worst,concave points_worst,perimeter_mean
0,17.99,2019.0,0.14710,184.60,0.2654,122.80
1,20.57,1956.0,0.07017,158.80,0.1860,132.90
2,19.69,1709.0,0.12790,152.50,0.2430,130.00
3,11.42,567.7,0.10520,98.87,0.2575,77.58
4,20.29,1575.0,0.10430,152.20,0.1625,135.10
...,...,...,...,...,...,...
564,21.56,2027.0,0.13890,166.10,0.2216,142.00
565,20.13,1731.0,0.09791,155.00,0.1628,131.20
566,16.60,1124.0,0.05302,126.70,0.1418,108.30
567,20.60,1821.0,0.15200,184.60,0.2650,140.10
568,7.76,268.6,0.00000,59.16,0.0000,47.92

In [47]:
df.isna().sum()
df.dropna(inplace=True)

In [48]:
df.duplicated().sum()

0

In [49]:

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=51)

In [50]:
 
classifier= LogisticRegression(random_state=10)

In [51]:
classifier.fit(x_train, y_train)

LogisticRegression(random_state=10)

In [52]:
#Predicting the test set result  
y_pred= classifier.predict(x_test)  
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0])

In [53]:
accuracy_score(y_test, y_pred)

0.956140350877193

In [54]:
#Creating the Confusion matrix  
from sklearn.metrics import confusion_matrix  
confusion_matrix(y_test,y_pred)

array([[74,  2],
       [ 3, 35]], dtype=int64)

In [55]:
#Hypertuning

from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings('ignore')

In [56]:
parameters={'penalty':('l1', 'l2','elasticnet'),'C':[1,10,20,30]}

In [57]:
classifier=LogisticRegression()

In [59]:
clf=GridSearchCV(classifier,param_grid=parameters,cv=5)
clf.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 10, 20, 30],
                         'penalty': ('l1', 'l2', 'elasticnet')})

In [60]:
clf.best_score_

0.9516483516483516

In [61]:
clf.best_params_

{'C': 30, 'penalty': 'l2'}

In [66]:
# Passing best parameters into model
classifier=LogisticRegression(C=30,penalty='l2')
classifier.fit(x_train,y_train)

LogisticRegression(C=30)

In [67]:
#Predicting the test set result  
y_pred= classifier.predict(x_test)  
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0])

In [68]:
#Creating the Confusion matrix  
from sklearn.metrics import confusion_matrix  
confusion_matrix(y_test,y_pred)

array([[75,  1],
       [ 3, 35]], dtype=int64)

In [69]:
# After data hypertuning the score of test data 
accuracy_score(y_test, y_pred)

0.9649122807017544